require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SaveTablesController do

  # This should return the minimal set of attributes required to create a valid
  # SaveTable. As you add validations to SaveTable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SaveTablesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all save_tables as @save_tables" do
      save_table = SaveTable.create! valid_attributes
      get :index, {}, valid_session
      assigns(:save_tables).should eq([save_table])
    end
  end

  describe "GET show" do
    it "assigns the requested save_table as @save_table" do
      save_table = SaveTable.create! valid_attributes
      get :show, {:id => save_table.to_param}, valid_session
      assigns(:save_table).should eq(save_table)
    end
  end

  describe "GET new" do
    it "assigns a new save_table as @save_table" do
      get :new, {}, valid_session
      assigns(:save_table).should be_a_new(SaveTable)
    end
  end

  describe "GET edit" do
    it "assigns the requested save_table as @save_table" do
      save_table = SaveTable.create! valid_attributes
      get :edit, {:id => save_table.to_param}, valid_session
      assigns(:save_table).should eq(save_table)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SaveTable" do
        expect {
          post :create, {:save_table => valid_attributes}, valid_session
        }.to change(SaveTable, :count).by(1)
      end

      it "assigns a newly created save_table as @save_table" do
        post :create, {:save_table => valid_attributes}, valid_session
        assigns(:save_table).should be_a(SaveTable)
        assigns(:save_table).should be_persisted
      end

      it "redirects to the created save_table" do
        post :create, {:save_table => valid_attributes}, valid_session
        response.should redirect_to(SaveTable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved save_table as @save_table" do
        # Trigger the behavior that occurs when invalid params are submitted
        SaveTable.any_instance.stub(:save).and_return(false)
        post :create, {:save_table => {}}, valid_session
        assigns(:save_table).should be_a_new(SaveTable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SaveTable.any_instance.stub(:save).and_return(false)
        post :create, {:save_table => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested save_table" do
        save_table = SaveTable.create! valid_attributes
        # Assuming there are no other save_tables in the database, this
        # specifies that the SaveTable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SaveTable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => save_table.to_param, :save_table => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested save_table as @save_table" do
        save_table = SaveTable.create! valid_attributes
        put :update, {:id => save_table.to_param, :save_table => valid_attributes}, valid_session
        assigns(:save_table).should eq(save_table)
      end

      it "redirects to the save_table" do
        save_table = SaveTable.create! valid_attributes
        put :update, {:id => save_table.to_param, :save_table => valid_attributes}, valid_session
        response.should redirect_to(save_table)
      end
    end

    describe "with invalid params" do
      it "assigns the save_table as @save_table" do
        save_table = SaveTable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SaveTable.any_instance.stub(:save).and_return(false)
        put :update, {:id => save_table.to_param, :save_table => {}}, valid_session
        assigns(:save_table).should eq(save_table)
      end

      it "re-renders the 'edit' template" do
        save_table = SaveTable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SaveTable.any_instance.stub(:save).and_return(false)
        put :update, {:id => save_table.to_param, :save_table => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested save_table" do
      save_table = SaveTable.create! valid_attributes
      expect {
        delete :destroy, {:id => save_table.to_param}, valid_session
      }.to change(SaveTable, :count).by(-1)
    end

    it "redirects to the save_tables list" do
      save_table = SaveTable.create! valid_attributes
      delete :destroy, {:id => save_table.to_param}, valid_session
      response.should redirect_to(save_tables_url)
    end
  end

end
